// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmaceutical.DataAccess;

namespace Pharmaceutical.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210819080738_SeedContractTable")]
    partial class SeedContractTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pharmaceutical.Common.Models.ContractDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("ContractName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompanyApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVendorContractApproved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ContractDetails");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AssignedBy = "ToddPharmaceutical",
                            ContractId = 1,
                            ContractName = "Contract100",
                            IsCompanyApproved = false,
                            IsVendorContractApproved = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
